version: 2
jobs:
    build:
        working_directory: /tmp/repo 
        docker:
            - image: docker:17.09.1-ce-git
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
                version: 17.05.0-ce
            - run:
                name: Build Docker image
                command: docker build -t monosolutions/terraform:1.0.$CIRCLE_BUILD_NUM -t monosolutions/terraform:latest .
            - run: 
                name: push to repository
                command: |
                    echo $DOCKER_PASS | docker login  -u $DOCKER_USER --password-stdin
                    docker push monosolutions/terraform:1.0.$CIRCLE_BUILD_NUM
                    docker push monosolutions/terraform:latest
